name: wataruitoartwork
favicon: null
layout_spectrum: 0.04544
typography_spectrum: 1
title: "W's Artwork"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e9edf0'
    - '#050505'
    - '#c6c4b9'
    - '#aa755d'
    - '#4b311f'
  brandStrength: 0.8125
  lightness: 0.2193231990095228
  saturation: 0.5839057790581137
  rhythmicContrast: 0.5346838473342359
purpose: []
