name: wataruitoartwork
favicon: null
layout_spectrum: 0.02228661999106407
typography_spectrum: 0.11511103087104857
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.1745318891480565
  lightness: 0.2193231990095228
  saturation: 0.5839057790581137
  rhythmicContrast: 0.5346838473342359
purpose: []
